[package]
name = "popcircles-cli"
version = "0.0.0"
description = "CLI for finding the smallest circle on Earth containing a given share of world population"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
popcircles = { path = "../popcircles" }
serde_json.workspace = true
